Table "pg_user_attr" {
  "oid" "Oid" [pk, not null]
  "attrib_name" "NameData" [not null]
}

Table "pg_resource_attr" {
  "oid" "Oid" [pk, not null]
  "attrib_name" "NameData" [not null]
}

Table "pg_user_attr_val" {
  "user_id" "Oid" [pk, not null]
  "attr_id" "Oid" [pk, not null]
  "value" "Text" [not null]
}

Table "pg_resource_attr_val" {
  "resource_id" "Oid" [pk, not null]
  "attr_id" "Oid" [pk, not null]
  "value" "Text" [not null]
}

Table "pg_abac_rule_priv" {
  "rule_id" "Oid" [pk, not null]
  "rulename" "NameData" [not null]
  "privileges" "int32" [not null]
  "is_workday" "bool" [not null]
}

Table "pg_abac_rule" {
  "rule_id" "Oid" [pk, not null]
  "attr_id" "Oid" [pk, not null]
  "is_user_attr" "bool" [not null]
  "value" "Text" [not null]
}

Table "pg_abac_env_workday" {
  "day_of_week" "int16" [pk, not null]
  "is_workday" "bool" [not null]
}

Table "pg_authid"{
  "oid" "Oid" [pk, not null]
}

Table "pg_class"{
  "oid" "Oid" [pk, not null]
}

Ref "pg_user_attr_val_user_id":"pg_authid"."oid" < "pg_user_attr_val"."user_id"

Ref "pg_resource_attr_val_resource_id":"pg_class"."oid" < "pg_resource_attr_val"."resource_id"

Ref "pg_user_attr_val_attr_id_fkey":"pg_user_attr"."oid" < "pg_user_attr_val"."user_id"

Ref "pg_resource_attr_val_attr_id_fkey":"pg_resource_attr"."oid" < "pg_resource_attr_val"."resource_id"

Ref "pg_abac_rule_rule_id_fkey":"pg_abac_rule_priv"."rule_id" < "pg_abac_rule"."rule_id"

Ref "pg_abac_rule_user_attr_id_fkey":"pg_user_attr"."oid" < "pg_abac_rule"."attr_id"
Ref "pg_abac_rule_resource_attr_id_fkey":"pg_resource_attr"."oid" < "pg_abac_rule"."attr_id"
